export const DAYS = {
  0: "Sunday",
  1: "Monday",
  2: "Tuesday",
  3: "Wednesday",
  4: "Thursday",
  5: "Friday",
  6: "Saturday"
};

export const MONTHS = {
  0: "January",
  1: "February",
  2: "March",
  3: "April",
  4: "May",
  5: "June",
  6: "July",
  7: "August",
  8: "September",
  9: "October",
  10: "November",
  11: "December"
};

export const IMAGES = {
  "Thunderstorm": "thunderstorm-bg",
  "Drizzle": "drizzle-bg",
  "Rain": "rain-bg",
  "Snow": "snow-bg",
  "Clear": "clear-bg",
  "Clouds": "clouds-bg",
}

export const ICONS = {
  "Sunny": "sunny",
  "Clear": "clear",
  "Partly cloudy": "partly-cloudy",
  "Cloudy": "cloudy",
  "Overcast": "overcast",
  "Mist": "mist",
  "Patchy rain possible": "rain-possible",
  "Patchy snow possible": "snow-possible",
  "Patchy sleet possible": "sleet-possible",
  "Patchy freezing drizzle possible": "snow-possible",
  "Thundery outbreaks possible": "thunder-possible",
  "Blowing snow": "blowing-snow",
  "Blizzard": "blowing-snow",
  "Fog": "mist",
  "Freezing fog": "mist",
  "Patchy light drizzle": "patchy-light-drizzle",
  "Light drizzle": "patchy-light-drizzle",
  "Freezing drizzle": "patchy-light-drizzle",
  "Heavy freezing drizzle": "patchy-light-drizzle",
  "Patchy light rain": "patchy-light-rain",
  "Light rain": "light-rain",
  "Moderate rain at times": "moderate-rain-time",
  "Moderate rain": "moderate-rain",
  "Heavy rain at times": "heavy-rain-time",
  "Heavy rain": "heavy-rain",
  "Light freezing rain": "light-freezing-rain",
  "Moderate or heavy freezing rain": "light-freezing-rain",
  "Light sleet": "light-freezing-rain",
  "Moderate or heavy sleet": "light-freezing-rain",
  "Patchy light snow": "patchy-light-snow",
  "Light snow": "patchy-light-snow",
  "Patchy moderate snow": "patchy-light-snow",
  "Moderate snow": "patchy-light-snow",
  "Patchy heavy snow": "patchy-light-snow",
  "Heavy snow": "heavy-snow",
  "Ice pellets": "ice-pellets",
  "Light rain shower": "light-rain-shower",
  "Moderate or heavy rain shower": "light-rain-shower",
  "Torrential rain shower": "light-rain-shower",
  "Light sleet showers": "light-sleet-showers",
  "Moderate or heavy sleet showers": "light-sleet-showers",
  "Light snow showers": "light-sleet-showers",
  "Moderate or heavy snow showers": "light-sleet-showers",
  "Light showers of ice pellets": "light-pellets",
  "Moderate or heavy showers of ice pellets": "light-pellets",
  "Patchy light rain with thunder": "light-rain-thunder",
  "Moderate or heavy rain with thunder": "heavy-rain-thunder",
  "Patchy light snow with thunder": "light-snow-thunder",
  "Moderate or heavy snow with thunder": "heavy-snow-thunder"
}
